### ISSUE TITLE
Possibility to create custom variables to change in template file

### ISSUE THREAD

**Issue by alxndrhi** [alxndrhi/vhm#2]

**Comment by alxndrhi** [comment]
Ok, way better. Use Hooks. If a given hook.vhm File exist in the currently called folder, it will be triggert as well. So everyone can create as many custom variables as they want. Also additional tasks can be triggert.

**Comment by displayn** [comment]
:+1:

**Comment by alxndrhi** [comment]
Added --hook filename.sh option. now it is possible to give a shell script name that will be executed after vhm finished.
